feat: webpack copy
umijs/umi-next pull request #118
Opened 2021-09-14 02:24 UTC by xiaohuoni

2021-09-14 08:06 UTC, sorrycc requested changes

2021-09-14 08:06 UTC, sorrycc commented on packages/bundler-webpack/src/build.test.ts
> +    console.log(fixture)
删下，另外没走 prettier？

2021-09-14 08:06 UTC, sorrycc commented on packages/bundler-webpack/src/config/config.ts
> +  await applyCopyPlugin(applyOpts);
applyCopyPlugin > addCopyPlugin

2021-09-14 08:06 UTC, sorrycc commented on packages/bundler-webpack/compiled/copy-webpack-plugin/lazy-compilation-web.js
> +/* global __resourceQuery */
为啥会有这两个 lazy-compilation 文件，记得是 webpack 里的。

2021-09-14 08:06 UTC, sorrycc commented on packages/bundler-webpack/src/config/copyPlugin.ts
> +            to: absOutputPath,
1. copy 一定要带 to 属性吗？要的话也应该读 config.output.path
2. to 感觉更应该是相对路径

2021-09-16 02:45 UTC, xiaohuoni commented on packages/bundler-webpack/compiled/copy-webpack-plugin/lazy-compilation-web.js
> +/* global __resourceQuery */
![image](https://user-images.githubusercontent.com/11746742/133541091-d855e5b0-e45f-4c4a-a97e-bcedd9f65293.png)
这个我也不清楚，我是按命令执行的

2021-09-16 02:56 UTC, xiaohuoni commented on packages/bundler-webpack/src/config/copyPlugin.ts
> +            to: absOutputPath,
1、to 有默认值 `output.path`
2、可以是相对路径

2021-09-16 13:04 UTC, merged

2021-09-17 07:13 UTC, xiaohuoni commented on packages/bundler-webpack/compiled/copy-webpack-plugin/lazy-compilation-web.js
> +/* global __resourceQuery */
https://github.com/umijs/umi-next/pull/120