feat(preset-umi): support monorepo redirect
umijs/umi-next pull request #427
Opened 2022-03-04 16:09 UTC by fz6m

#### 问题

1. 解 monorepo 中的项目，去导其他子包的东西，改动子包源码不能热更新的问题

2. 同样的，也解 MFSU 场景缓存了这些子包，无法热更新的问题

#### 实现

实现手段是通过 workspace 工具（changesets 底层工具）扫出来全部子包，之后和本项目引用的依赖取交集得到需要重定向的子包们，把他们的 `alias` 改到这些子包的源码文件夹，默认为 `src` 。

#### 可配置

同时支持 `排除不需要定位的子包`，和用户的源码不在 `src` 时，要定位的文件夹优先级顺序，如有的组件库可能放到了 `libs`

2022-03-08 04:10 UTC, sorrycc requested changes

2022-03-08 04:10 UTC, sorrycc commented on packages/preset-umi/src/features/monorepo/redirect.ts
> +      schema(joi) {
joi > Joi，统一格式。

2022-03-08 04:10 UTC, sorrycc commented on packages/preset-umi/src/features/monorepo/redirect.ts
> +        return joi.alternatives(
不用处理 false 值，所有插件功能都支持设为 false。

2022-03-08 04:10 UTC, sorrycc commented on packages/preset-umi/src/features/monorepo/redirect.ts
> +            source: joi.array().items(joi.string()),
source > srcDir

2022-03-08 04:10 UTC, sorrycc commented on packages/preset-umi/src/features/monorepo/redirect.ts
> +    exclude.push(/^umi$/);
为啥要特殊处理 umi ？通常项目也不会有这个。

2022-03-08 04:10 UTC, sorrycc commented on packages/preset-umi/src/features/monorepo/redirect.ts
> +    if (!isMonorepo({ root })) return memo;
不是 monorepo 显式抛错吧，说明「用户不应该配这个」。

2022-03-08 04:10 UTC, sorrycc commented on packages/preset-umi/src/features/monorepo/redirect.ts
> +    if (!isMonorepo({ root })) return memo;
不是 monorepo 显式抛错吧，说明「用户不应该配这个」。

2022-03-08 04:10 UTC, sorrycc commented on packages/preset-umi/src/features/monorepo/redirect.ts
> +    if (!isMonorepo({ root })) return memo;
不是 monorepo 显式抛错吧，说明「用户不应该配这个」。

2022-03-08 04:10 UTC, sorrycc commented on packages/preset-umi/src/features/monorepo/redirect.ts
> +    if (memo.monorepoRedirect === false) return memo;
这行可以删了，如果用户没有配 monorepoRedirect，不会走到 api.modifyConfig 里的。

2022-03-08 04:10 UTC, sorrycc commented on packages/preset-umi/src/features/monorepo/redirect.ts
> +function collectWorkspaceDeps(pkg: Record<string, any>) {
看实现是搜集所有依赖，没有判断 workspace，为啥叫 collectWorkspaceDeps？

2022-03-08 04:10 UTC, sorrycc commented on packages/preset-umi/package.json
> +    "@manypkg/get-packages": "1.1.3",
做个预打包。

2022-03-08 05:58 UTC, fz6m commented on packages/preset-umi/src/features/monorepo/redirect.ts
> +    exclude.push(/^umi$/);
现在改成：本地调试需要排除一下，不然直接把 umi 当成 ts 处理会报错

2022-03-08 05:59 UTC, fz6m commented on packages/preset-umi/package.json
> +    "@manypkg/get-packages": "1.1.3",
这个包 ts 写的，不符合那个默认的声明文件寻找逻辑，打不出来 `.d.ts` ，可以看下。。

2022-03-09 07:32 UTC, sorrycc commented on docs/docs/api/config.md
> +* 类型：`{ source?: string[], exclude?: RegExp[] }`
```suggestion
* 类型：`{ srcDir?: string[], exclude?: RegExp[] }`
```

2022-03-09 07:34 UTC, sorrycc commented
其他没问题了，merge master 修下冲突。

2022-03-09 09:14 UTC, merged