feat(api-route): Dynamic API route
umijs/umi-next pull request #450
Opened 2022-03-09 07:36 UTC by ken20001207

让 API 路由功能支持动态匹配，例如：

```
examples/api-route-demo/src
├── api
│   ├── index.ts
│   └── users
│       ├── [userId]
│       │   ├── index.ts
│       │   └── repos
│       │       ├── [repoId].ts
│       │       └── index.ts
│       └── index.ts
└── pages
    └── index.tsx
```

这样的目录结构可以实现出这样的 API 设计：

- `/api/users`：用户列表
- `/api/users/:userId` 某个用户的数据
- `/api/users/:userId/repos` 某个用户的仓库列表
- `/api/users/:userid/repos/:repoId` 某个用户的某个仓库的数据

2022-03-09 07:37 UTC, ken20001207 commented
WIP: `umi dev` 已可使用动态路由，但 Vercel Adapter 尚未实现

2022-03-09 08:57 UTC, ken20001207 commented
Vercel Adapter 做好了 https://github.com/umijs/umi-next/pull/450/commits/366469558b5a47d447b430064b30dc05687aecce

2022-03-09 10:01 UTC, sorrycc requested changes

2022-03-09 10:15 UTC, ken20001207 commented on packages/preset-umi/src/features/apiRoute/utils.ts
> +export function matchApiRoute(
已加 👍 [7e4675b](https://github.com/umijs/umi-next/pull/450/commits/7e4675b4c1652fcbdda72d859f32a08e961390eb)

2022-03-09 10:28 UTC, ken20001207 commented on packages/preset-umi/src/features/apiRoute/vercel/esbuild.ts
> +          '^/api/' + r.path.replace(/\[(.*?)]/g, '(?<$1>[^/]+?)') + '(?:/)?$',
已加 👍 [f72f42e](https://github.com/umijs/umi-next/pull/450/commits/f72f42e0ebdc5de7d818ce1cfe9edecd4c862040)

2022-03-10 00:47 UTC, sorrycc commented on packages/preset-umi/src/features/apiRoute/utils.ts
> +export function matchApiRoute(
加下测试用例，新增一个 utils.test.ts。

2022-03-10 05:40 UTC, ken20001207 commented on packages/preset-umi/src/features/apiRoute/utils.ts
> +export function matchApiRoute(
已加 👍 [20af5cd](https://github.com/umijs/umi-next/pull/450/commits/20af5cd5203af3e7194ebc3eb5ccaa16868a666f) 顺便修了个测试到的 bug

2022-03-10 05:51 UTC, merged