feat(lint): add umi lint feature
umijs/umi-next pull request #536
Opened 2022-03-24 10:09 UTC by devilmancbc

## description

支持 umi lint 命令，改动点如下：

1. 新增 `@umijs/lint` 子包，包含：
  a. stylelint 推荐配置：继承自 fabric，增加 css-in-js 支持
  b. eslint 推荐配置：不继承任何 recommended 配置，直接把需要开启的校验规则打包；同时无需再挂载 `eslint-config-prettier` 等配置，减小安装体积
  c. eslint 兼容配置：如果开发者使用新的 eslint 默认配置迁移项目时遇到卡点，可以切换到 legacy 配置（不推荐）
  b. linter 驱动模块：根据上层配置自动驱动 stylelint 及 eslint 执行，且支持同一套 glob 表达式按文件类型分流
2. 新增 `umi lint` 命令：
  a. 支持参数：`umi lint [glob] [--css-in-js] [--fix] [--eslint-only] [--stylelint-only]`
  b. 包含 glob 默认值： `{src,test}/**/*.{js,jsx,ts,tsx,less,css}`
5. umi 及 max 包增加 `xxx/eslint` 及 `xxx/stylelint` 导出供用户使用，可通过 `LEGACY_ESLINT` 环境变量切换到 eslint 兼容配置

2022-03-28 01:47 UTC, PeachScript commented on examples/lint/package.json
> +    "lint:es --fix": "umi lint '*.js' --eslint-only --fix",
`lint:es-fix`，下同；`lint:fix` 可以去掉

2022-03-28 01:47 UTC, PeachScript commented on examples/lint/testts.ts
> +var a = 1;
加一些类型，否则和 js 无异

2022-03-28 01:47 UTC, PeachScript commented on examples/lint/testjs.js
> +var a= 1;
等号前的空格如果是故意缺失，加个注释 `// expect space missing error`

2022-03-28 01:47 UTC, PeachScript commented on packages/lint/src/index.ts
> +  console.log('opts-----------------');
log 去掉

2022-03-29 11:21 UTC, PeachScript commented on packages/lint/src/index.ts
> +    args._.unshift('--ignore-pattern', '*.ts');
直接传 `*.{js,jsx,ts,tsx}`？

以及代码块内也要保持变量声明在主逻辑上面

2022-03-29 11:21 UTC, PeachScript commented on packages/lint/src/index.ts
> +    args._.unshift('--ignore-pattern', '*.less');
`{css,less,sass,scss,styl}`

2022-03-30 06:23 UTC, PeachScript commented on examples/lint/tsconfig.json
> +  "extends": "./tsconfig.base.json",
不需要拆成两个 json，参考 bigfish example 下的 tsconfig、合并成一个

2022-03-30 06:23 UTC, PeachScript commented on packages/lint/src/config/stylelint/index.ts
> +    require.resolve('@stylelint/postcss-css-in-js'),
css-in-js 不是配置，不需要 extends

2022-03-30 06:23 UTC, PeachScript commented on packages/lint/src/config/stylelint/index.ts
> +        '**/*.js',
我理解 `**/*.js` 应该是包括 `*.js` 的，可以验证下

2022-03-30 06:23 UTC, PeachScript commented on packages/lint/src/config/stylelint/index.ts
> +      customSyntax: '@stylelint/postcss-css-in-js',
这个包没安装，以及使用 require.resolve

2022-03-30 06:23 UTC, PeachScript commented on packages/lint/src/index.ts
> +      args._.unshift('--ignore-pattern', '*.js');
- 不能只匹配顶层的文件
- 参数不能合并成一个 `**/*.{js,jsx,ts,tsx}` 吗？

2022-03-30 06:23 UTC, PeachScript commented on packages/lint/src/index.ts
> +  return '@umijs/lint';
return 语句以及对应的测试文件可以先删掉，不然 CI 会挂

2022-03-30 07:00 UTC, devilmancbc commented on packages/lint/src/index.ts
> +      args._.unshift('--ignore-pattern', '*.js');
我试过合并成一个 **/*.{js,jsx,ts,tsx} 就不能识别这些文件了

2022-03-31 04:06 UTC, PeachScript commented on examples/lint/package.json
> +    "@stylelint/postcss-css-in-js": "^0.37.2",
这个安装到 lint 里，还需要额外安装 `postcss-syntax`

2022-03-31 04:08 UTC, PeachScript commented on packages/lint/src/config/stylelint/index.ts
> +    require.resolve('postcss-syntax'),
这个不需要

2022-03-31 04:09 UTC, PeachScript commented on packages/lint/src/index.ts
> +      args._.unshift('--ignore-pattern', '**/*.js');
改成 for 循环，把后缀名提成顶层常量

2022-03-31 06:53 UTC, PeachScript commented on packages/lint/src/index.ts
> +      '**/*styl',
```suggestion
      '**/*.styl',
```

这两个常量提到这个文件的顶层， 插在第 3 行；以及常量名写反了，`STYLE_ETXS` 代表样式相关的后缀名

2022-03-31 08:17 UTC, sorrycc requested changes
1、--cssinjs 是干啥的？
2、export 的文件不要加 config- 前缀吧，比如用 umi/eslint，比如 umi/test 也没有加
3、有没有办法只 export 一个文件，通过配置的方式支持 legacy
4、umi 和 max 的 files 都没有包含新增的文件
5、为啥加 api.modifyLinterOpts？什么地方会用？
6、@umijs/lint 的依赖有点多，都是必须的吗？会增加多少包尺寸？@babel/core 不要单独依赖
7、TYPE_AWARE_ENABLE 的规则还有必要吗？我们梳理后的规则应该没有 type 相关的吧

2022-03-31 08:19 UTC, sorrycc commented
umi/eslint-legacy 不要了，统一到 umi/eslint 里，通过环境变量区分 。

2022-04-01 14:23 UTC, merged