feat(ssr): Add Server-Side Rendering and Data Prefetch
umijs/umi-next pull request #540
Opened 2022-03-25 09:25 UTC by ken20001207

这个 PR 实现了两个 feature ：**服务端渲染** 和 **数据预加载**。

# 服务端渲染

就是常见的服务端渲染，可以优化 SEO、提升首屏渲染速度、针对请求渲染不同的内容。

## 开启方式

配置开启。

```ts
// .umirc.ts

export default {
  ssr: {},
};
```

## 使用方式

开启了以后，在页面组件内新增一个函数 `loader` 并导出，这个函数会在请求时被运行，然后函数返回值可以在页面中使用 `useLoaderData` 这个 hook 获取：

```ts
// pages/index.tsx

import React from 'react';
import { useLoaderData } from 'umi';

export default () => {
  const loaderData = useLoaderData();
  return (
    <div>
      <p>loader data: {JSON.stringify(loaderData)}</p>
    </div>
  );
};

export async function loader() {
  return { message: 'data from server loader of users/user.tsx' };
}
```

在 `umi build` 时，除了 `dist` 目录外，还会在 `server` 目录下生成 `umi.server.js` 文件，你可以将这个文件作为中间件的方式使用在 Express 后端服务中。

```js
// server/index.js

const express = require('express');
const app = express();
const port = 3000;

// Umi SSR middleware
app.use(require(__dirname + '/umi.server.js').default);

// static files
app.use(express.static('dist'));

// Start server
app.listen(port, () => {
  console.log(`Server is now running at http://127.0.0.1:${port}/`);
});
```

访问 `http://127.0.0.1:3000/` 就可以看到服务端渲染的页面。

## TODO

- [x] 让用户可以配置构建产物的导出地址。
- [x] 支持开发模式 `umi dev` 下使用
- [ ] 让用户可以在 `loader` 访问 Http 的 request 对象。
- [ ] 除了 Express 中间件之外，更多的使用方式。
- [ ] 支持 css-in-js (emotion / antd v5)
- [x] 打包客户端产物的时候，要把 loader 和 clientLoader 的代码（及其依赖）丢掉

# 数据预加载

考虑到可能很多复杂的中台项目会有页面组件很复杂导致加载时间很长，而页面需要的数据加载时间也很长的问题，提出了一个优化方案，在用户切换页面的时候，同时请求页面组件和页面需要的数据，这样就可以并行加载来减少等待时间。

## 对比

```ts
/** 假设这是一个很复杂的页面组件，需要花费 10 秒才能加载完成组件的 js 代码 */
export default function SomeHugePage() {

	const [data, setData] = useState();

	useEffect(() => {
		refresh();
	}, []);

	async function refresh() {

		/** 假设这是一个很大的数据，需要花费 10 秒才能加载完成 */
		const res = await fetch('https://api.example.com/a_big_data');
		const data = await res.json();
		setData(data);

	}

	return <div>

		{/** 打开页面后，你至少需要等待 20 秒才能看到数据 */}
		<p>{data}</p>

		<button onClick={refresh}>
			Refrsh
		</button>

		<SomeHugeComponents />
	</div>
}
```

在上面这个场景，我们需要花 10 秒加载组件的 js 代码，然后加载完毕后组件再花 10 秒加载数据，一共等待了 20 秒才看到最后的渲染结果。

```ts
/** 这个函数会在 SomeHugePage 被加载时同时开始运行 */
export function clientLoader() {

	/** 假设这是一个很大的数据，需要花费 10 秒才能加载完成 */
	const res = await fetch('https://api.example.com/a_big_data');
	return await res.json();

}

/** 假设这是一个很复杂的页面组件，需要花费 10 秒才能加载完成组件的 js 代码 */
export default function SomeHugePage() {

	const clientLoaderData = useClientLoaderData();

	return <div>

		{/** 打开页面后，你最快只要等待 10 秒就能看到数据 */}
		<p>{clientLoaderData}</p>

		<SomeHugeComponents />
	</div>
}
```

从上面的范例中，透过 `clientLoader` 的功能，我们并行加载组件代码和组件需要的数据，所以只要等待 10 秒就能看到最后的渲染结果。

## TODO

- [ ] 支持主动从组件内重新发起 clientLoader 的请求（刷新数据）

2022-03-30 02:25 UTC, sorrycc requested changes
其他，

1、umi.server.js 放 server 目录感觉不太好，建议放 dist，原因是作为产物，不应该被提交，用户需要额外在 .gitignore 里添加 server/umi.server.js，不太好

2、tsc 问题 merge 下 master

2022-03-30 02:25 UTC, sorrycc commented on packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
> +        ).join(', ')} } from '${rendererReactPath}/dist/index.js';`,
有需要的话，把 rendererReactPath 直接改成 winPath(require.resolve('@umijs/renderer-react')，不用每个地方加 dist/index.js。

2022-03-30 02:25 UTC, sorrycc commented on packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
> +      clonedRoutes[id].hasLoader = exports.includes('loader');
参考 https://remix.run/blog/remixing-react-router，直接给路由加 loader 属性会不会更好？同时也方便后期直接用 react-router 内部处理 loader 的功能。

2022-03-30 02:25 UTC, sorrycc commented on packages/preset-umi/src/features/ssr/ssr.ts
> +    const rendererPath = winPath(
这里的文件生成逻辑放到 tmpFile.ts 里吧，rendererPath、clonedRoutes 都处理了两遍，不太好。可以在 tmpFile.ts 里判断 api.config.ssr 决定是否生成这些文件。

2022-03-30 02:41 UTC, ken20001207 commented on examples/ssr-demo/package.json
> +    "umi": "4.0.0-canary.20220318.1"
[efb30c4](https://github.com/umijs/umi-next/pull/540/commits/efb30c4f9af3915f1ff19e7308603f3d032b7eeb) 已改 👍

2022-03-30 02:45 UTC, ken20001207 commented on packages/preset-umi/templates/history.tpl
> +import { createHashHistory, createMemoryHistory, createBrowserHistory, History } from '{{{ rendererPath }}}/dist/index.js';
esbuild 在这种用法会报错：

<img width="1565" alt="Screen Shot 2022-03-30 at 10 43 09 AM" src="https://user-images.githubusercontent.com/21105863/160740412-172586f3-3b4e-4acc-94fc-0a8b05da07af.png">

还是我试试从 esbuild 插件去解，让他遇到目录的话就直接去找目录下的 `dist/index.js` ？

2022-03-30 02:48 UTC, sorrycc commented on packages/preset-umi/templates/history.tpl
> +import { createHashHistory, createMemoryHistory, createBrowserHistory, History } from '{{{ rendererPath }}}/dist/index.js';
可以改成加 dist/index.js，但是从源头上改吧。

2022-03-30 02:58 UTC, ken20001207 commented on packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
> +        ).join(', ')} } from '${rendererReactPath}/dist/index.js';`,
https://github.com/umijs/umi-next/pull/540/commits/05355fa7b269b3097d7aef9a6bfe79504193cb5e 已改 👍

2022-03-30 02:58 UTC, ken20001207 commented on packages/preset-umi/templates/history.tpl
> +import { createHashHistory, createMemoryHistory, createBrowserHistory, History } from '{{{ rendererPath }}}/dist/index.js';
https://github.com/umijs/umi-next/commit/05355fa7b269b3097d7aef9a6bfe79504193cb5e 已改 👍

2022-03-30 03:44 UTC, ken20001207 commented on packages/preset-umi/src/features/ssr/utils.ts
> +export async function getRouteModuleExports(
[ee969d9](https://github.com/umijs/umi-next/pull/540/commits/ee969d9e247bfd56498c6015cc763aadf7d23576) 已加 👍

加完发现下面两个函数 `getRouteLoader` 和 `getRouteClientLoader` 的逻辑其实差不多，只是导出形式不同，所以直接合在一起了。

2022-03-30 06:25 UTC, ken20001207 commented on packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
> +      clonedRoutes[id].hasLoader = exports.includes('loader');
[6f7e39b](https://github.com/umijs/umi-next/pull/540/commits/6f7e39be9cb5685677103d04c6ac7681006341c3) 已改 👍

不过 `hasLoader` 指的是有没有服务端的 loader，也就是当加载这个路由时需不需要发起 `__umi?route=key` 请求。

这个 commit 加入的 `route.loader` 是 clientLoader，也就是取代本来传入 `renderClient` 的 `opts.clientLoaders`

2022-03-30 06:38 UTC, ken20001207 commented on packages/preset-umi/src/features/ssr/ssr.ts
> +    const rendererPath = winPath(
[55b07f0](https://github.com/umijs/umi-next/pull/540/commits/55b07f0f4249b8e1467846e0f0214ba7b81d367d) 已改 👍

2022-03-30 06:50 UTC, ken20001207 commented on packages/renderer-react/src/browser.tsx
> +export async function getClientRootComponent(opts: {
[2f09a10](https://github.com/umijs/umi-next/pull/540/commits/2f09a10fcac422d64714fa9d9dabea238c70135b) 已改 👍

2022-03-30 06:52 UTC, ken20001207 commented
> 1、umi.server.js 放 server 目录感觉不太好，建议放 dist，原因是作为产物，不应该被提交，用户需要额外在 .gitignore 里添加 server/umi.server.js，不太好

放 `dist` 的话，服务端产物 `umi.server.js` 会被下一步的客户端产物 `umi.js`, `index.html` ... 覆盖掉
 
> 2、tsc 问题 merge 下 master

已 merge 👍

2022-03-30 10:47 UTC, ken20001207 commented
[1aaf2d4](https://github.com/umijs/umi-next/pull/540/commits/1aaf2d44f4360560d44aa33c4fe7619663674ec9)

在 webpack 做最后打包以前，会先用 esbuild 把 routes 的 component 做一次初步的打包，保存到 `.umi/pages` 目录下，
这是为了让 esbuild 把我们不要打包到客户端产物的 `loader` 和 `clientLoader` 丢掉，只提取出 `default`。

在 `.umi/core/route.tsx` 中，原本的 routeComponents 是从页面组件的原代码文件动态引入，现在则是从 `.umi/pages` 引入。

### 已知问题

这个方案目前在 `example/ssr-demo` 可以跑通，但在 `plugin-docs` 会出问题，有待解决。

2022-04-15 04:17 UTC, sorrycc commented on packages/bundler-webpack/src/config/manifestPlugin.ts
> -  if (userConfig.manifest) {
这个不要删，ssr 时同时配就好。

2022-04-15 04:38 UTC, sorrycc commented on packages/preset-umi/src/features/tmpFiles/routes.ts
> +      if (isPluginDocsEnable) {
这段逻辑不太清楚。

1、为啥 plugin docs 要区分处理？
2、route.file.startsWith('(') 时应该保持之前的逻辑，直接编译，不拆分

2022-04-15 04:39 UTC, sorrycc commented on packages/preset-umi/src/index.ts
> +      require.resolve('./features/tmpFiles/tmpFiles'),
调整顺序是有前后依赖吗？有依赖需注明，否则默认按字母排序。

2022-04-15 04:42 UTC, sorrycc commented on packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
> +        hydrate: !!api.userConfig.ssr,
用 api.config.ssr。

2022-04-15 04:44 UTC, sorrycc commented on packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
> +    try {
什么场景会报错？不要静默把错误藏起来。

2022-04-15 04:45 UTC, sorrycc commented on packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
> +    if (api.userConfig.ssr) {
api.config.ssr

2022-04-15 04:53 UTC, sorrycc commented on packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
> +  if (!isPluginDocsEnable) {
plugin docs 不兼容的原因是？

2022-04-15 06:16 UTC, ken20001207 commented on packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
> +  if (!isPluginDocsEnable) {
@sorrycc plugin docs 的页面路由是 mdx 文件， mdx 文件内是不会有 loader 和 clientLoader 的，所以这边直接跳过了。

2022-04-15 06:24 UTC, ken20001207 commented on packages/preset-umi/src/index.ts
> +      require.resolve('./features/tmpFiles/tmpFiles'),
刚开始的时候有前后依赖，后来改写法以后没问题了，我把顺序改回去。

2022-04-15 06:35 UTC, ken20001207 commented on packages/bundler-webpack/src/config/manifestPlugin.ts
> -  if (userConfig.manifest) {
这个我直接 Revert 掉了，SSR 用的是另一个插件，所以这个不用改 👍

2022-04-15 06:42 UTC, ken20001207 commented on packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
> +        hydrate: !!api.userConfig.ssr,
已修复 👍

2022-04-15 06:43 UTC, ken20001207 commented on packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
> +    if (api.userConfig.ssr) {
已修复 👍

2022-04-15 06:52 UTC, ken20001207 commented on packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
> +    try {
因为这一步会调用 esbuild 去解析 ts(x) 文件，然后从解析的结果拿到 exports，但如果文件本身有语法问题导致 esbuild 解析失败的话，这里就会报错。

原本的想法是，如果真的解析失败，不应该是这里报错，因为这个 function 的工作只是帮忙提取 exports，语法错误的报错应该让下一步的 webpack 或 esbuild 真的打包的时候才抛出来。

但刚刚把这里改了，如果解析失败的话就会从这里报错 👍

2022-04-15 06:59 UTC, ken20001207 commented on packages/preset-umi/src/features/tmpFiles/routes.ts
> +      if (isPluginDocsEnable) {
@sorrycc 这个和下面那个问题一样，因为 plugin-docs 的页面组件是从 mdx 转化而来，所以不需要用 esbuild 进行 pre-compile 提取出页面组件（丢掉 loader 和 clientLoader），因为从 mdx 转化而来的页面本来就不会导出 loader 和 clientLoader。

这边的逻辑是，如果 plugin-docs 开启了，那么代表不需要将路径改为 `preCompiledPath`。

2022-05-20 09:01 UTC, ken20001207 commented
Moved to #764 and #794

2022-05-20 09:01 UTC, closed without merging