docs: change tutorials/blog.md
umijs/umi-next pull request #552
Opened 2022-03-30 09:35 UTC by wjx0820

跟着教程操作，发现用微生成器页面会报错，需将umirc中的配置先注释

2022-04-11 11:36 UTC, PeachScript commented
> 发现用微生成器生成页面会报错

报错能贴一下吗，感觉应该解报错而不是绕过报错

2022-04-11 11:37 UTC, PeachScript requested changes
block

2022-04-11 11:45 UTC, wjx0820 commented
<img width="747" alt="image" src="https://user-images.githubusercontent.com/31770433/162732859-2dfa1146-3508-4cd4-bcfe-a9cf736f3db2.png">

2022-04-11 11:52 UTC, PeachScript commented
> <img alt="image" width="747" src="https://user-images.githubusercontent.com/31770433/162732859-2dfa1146-3508-4cd4-bcfe-a9cf736f3db2.png">

@stormslowly `g` 命令依赖 routes 生成吗？

2022-04-12 14:34 UTC, sorrycc commented
如果是 bug，直接修吧，不要改文档绕过。

2022-04-12 14:34 UTC, closed without merging