支持 https
umijs/umi-next pull request #553
Opened 2022-03-30 10:20 UTC by hangyangws

1. 支持配置 https: { key, cert, hosts } 开启，并可通过 key 和 cert 指定公私钥，可通过 hosts 指定绑定到本地进行调试的 host（hocalhost + 127.0.0.1） 地址
2. 如果没有配 key 或 cert，提醒用户，并通过 mkcert -cert-file umi.pem -key-file umi.key.pem hosts.join(' ') 自动生成到 __dirname 文件夹
3. 如果没有 mkcert，提示用户安装，如果是 Mac，推荐用 brew install mkcert + brew install nss + mkcert -install 三行命令，如果是 Windows，引导到 https://github.com/FiloSottile/mkcert#windows，如果是 Linux，引导到 https://github.com/FiloSottile/mkcert#linux

2022-03-30 13:53 UTC, sorrycc requested changes

2022-03-30 13:53 UTC, sorrycc commented on packages/bundler-webpack/src/utils/server.ts
> +  }
加个 else，显式报错吧。

2022-03-30 16:51 UTC, hangyangws commented on packages/bundler-webpack/src/utils/server.ts
> +              reject({});
reject 内容：证书和密钥生成失败。

2022-03-31 02:51 UTC, merged

2022-03-31 08:53 UTC, sorrycc commented
新开个 pr 补下 https 的配置文档。