feat(lint): add jest version and override
umijs/umi-next pull request #685
Opened 2022-04-25 09:06 UTC by devilmancbc

2022-04-25 11:20 UTC, PeachScript commented on packages/lint/src/config/eslint/index.ts
> +    jest: {
这个也加到 overrides 里

2022-04-26 09:30 UTC, PeachScript commented on packages/lint/src/config/eslint/index.ts
> +      files: ['*.{test,spec,unit,e2e}.{ts,tsx,js,jsx}'],
`**/*`

2022-04-26 10:33 UTC, devilmancbc commented on packages/lint/src/config/eslint/index.ts
> +      files: ['*.{test,spec,unit,e2e}.{ts,tsx,js,jsx}'],
done

2022-04-26 11:27 UTC, PeachScript requested changes

2022-04-26 11:27 UTC, PeachScript commented on packages/lint/src/config/eslint/index.ts
> +      jest: {
嵌套进 `settings`

2022-04-26 12:38 UTC, PeachScript approved these changes

2022-04-26 12:39 UTC, merged