feat: ClientLoader (Data Prefetch)
umijs/umi-next pull request #764
Opened 2022-05-11 02:38 UTC by ken20001207

从 #540 把 client loader 的部分分离出来

2022-05-11 05:17 UTC, sorrycc requested changes

2022-05-11 08:32 UTC, ken20001207 commented on packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
> +    const routes = await getRoutes({ api });
@sorrycc 改好了 👍

2022-05-17 10:07 UTC, merged

2022-05-18 12:52 UTC, fz6m commented on packages/preset-umi/src/features/tmpFiles/routes.ts
> +      const isJSFile = /.[jt]sx?/.test(file);
这个地方，是不是这样更好点：

```ts
const isJSXFile = /\.[jt]sx?$/.test(file);
```

2022-05-18 12:52 UTC, fz6m commented on packages/preset-umi/src/features/tmpFiles/routes.ts
> +      if (route.hasClientLoader) {
这段代码有啥用么。有个 `__hasClientLoader` ，但是没有 `hasClientLoader` 吧。

2022-05-18 12:55 UTC, fz6m commented on packages/renderer-react/src/browser.tsx
> +      return opts.history.listen((e) => {
这个地方，可以事先看看，假如没用 `clientLoader` ，最好就不要每次切换都做一次 match url ，浪费的。

2022-05-18 12:57 UTC, fz6m commented on packages/renderer-react/src/browser.tsx
> +            clientLoader().then((data: any) => {
一般事先拿数据的时候会考虑根据 url query 来取，建议 todo 后面增强下默认传参

2022-05-18 12:59 UTC, fz6m commented on packages/renderer-react/src/browser.tsx
> +          if (clientLoader && !clientLoaderData[id]) {
目前是只要匹配过的 `location.pathname` 就有 `clientLoaderData` 了，但是下次通过某些手段（比如 `history.push`）带不同的 query 进来，那这个数据就是旧的，不太合理 🤔 。

我觉得应该需要用 `location.href` 之类的当唯一 hash key 去让他即时失效。

2022-05-18 13:00 UTC, fz6m commented on examples/diff-client-loader/package.json
> +    "umi": "4.0.0-rc.17"
这俩 example 的 version 同步下最新的 version，不然跑不起来。